version: "3"
services:
  postgres:
    image: postgres
    container_name: "myapp_postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
  myapp_app:
    build: .
    command: >
      sh -c "npm run createdb 
      && npm run dev"
    container_name: "myapp_app"
    volumes:
      - .:/usr/app/
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - DATABASE=myapp
      - PORT=3000
    depends_on:
      - postgres